### ISSUE TITLE
Cannot find Data_Transformation.xlsx

### ISSUE THREAD

**Issue by ahbucknell** [koosfick/NEIC1.0#1]
Hello

After successfully installing NEIC1.0 I'm trying to run a test. However I cannot find where the necessary "Data_Transformation.xlsx" file is? The README states it is provided, but I cannot find it within the repository, bioRxiv paper, installer, or application. Not sure if I'm missing something very obvious here.

Trying to run this on a M2 Macbook Pro if this might be a platform-specific issue.

**Comment by koosfick** [comment]
Hi @ahbucknell. Thanks for the heads up. The file has been uploaded to the repository. If you experience any further issues, please don’t hesitate to reach out.

**Comment by ahbucknell** [comment]
Thank you very much for adding it to the repo @koosfick. I'll close this issue now.
